-- The Build Up — Seed Data (63 leads)
-- Run this in Supabase SQL Editor AFTER running supabase-schema.sql

INSERT INTO leads (name, business, category, what_they_do, revenue, twitter, linkedin, email, website, location, interview_angle, status) VALUES

-- MICRO-SAAS (19)
('Bhanu Teja P.', 'SiteGPT', 'Micro-SaaS', 'AI chatbot that trains on your website content for customer support', '$15K+ MRR', '@pbteja1998', 'linkedin.com/in/pbteja1998', '', 'sitegpt.ai', '', '24-year-old solo founder from India, bootstrapped to impressive scale', 'not_contacted'),
('Kyle Nolan', 'ProjectionLab', 'Micro-SaaS', 'Financial planning calculator for the FIRE community', '$50K+ MRR', '@_knolan', 'linkedin.com/in/kylecnolan', '', 'projectionlab.com', '', 'Built nights/weekends for 2 years, niche community focus drove deep product-market fit', 'not_contacted'),
('Dominik Sobe', 'HelpKit', 'Micro-SaaS', 'Turns Notion docs into professional help centers with AI chatbot', '$5K+ MRR', '@sobedominik', 'linkedin.com/in/dominik-sobe', '', 'helpkit.so', '', 'Digital nomad/surfer building SaaS from anywhere in the world', 'not_contacted'),
('Dmytro Krasun', 'ScreenshotOne', 'Micro-SaaS', 'Screenshot API for developers', '$21K MRR ($269K ARR)', '@DmytroKrasun', '', '', 'screenshotone.com', '', '17 years coding experience, SEO-driven growth, builds in public on Twitter', 'not_contacted'),
('Wilson Wilson & Olly Meakings', 'Senja', 'Micro-SaaS', 'Testimonial collection and display platform', '$83K+ MRR, 3000+ customers', '@euboid', '', '', 'senja.io', '', 'Remote co-founder duo, zero investors, built entirely in public', 'not_contacted'),
('Julien Nahum', 'NotionForms', 'Micro-SaaS', 'Form builder integrated with Notion API', '$10K+ MRR (~$200K ARR)', '@jhumanj', 'linkedin.com/in/julien-nahum', '', 'notionforms.io', '', 'Left Amazon to bootstrap, 14 months to $10K MRR milestone', 'not_contacted'),
('Sagar Patil', 'SSL Zen', 'Micro-SaaS', 'WordPress plugin for free SSL certificate generation', '$10K MRR', '', '', '', 'sslzen.com', '', 'WordPress ecosystem success, security niche, under 2 years to profitability', 'not_contacted'),
('Charanjit Singh', 'Indie Kit', 'Micro-SaaS', 'Next.js SaaS boilerplate with payments and multi-tenancy', '$6K+ revenue, 100+ signups', '', 'linkedin.com/in/charanjit-singh', '', 'indiekit.pro', '', 'Reddit-only marketing strategy, zero paid ads', 'not_contacted'),
('Cameron Trew', 'Kleo / Mentions', 'Micro-SaaS', 'LinkedIn trending data tool + AI brand mention tracker', '$62K MRR (Kleo) + $20K MRR (Mentions)', '', '', '', 'camerontrew.com', '', 'Quit job, moved in with parents, went from $0 to $62K MRR in 3 months', 'not_contacted'),
('Tony Dinh', 'TypingMind', 'Micro-SaaS', 'Better UI for ChatGPT/LLM APIs with team features and plugins', '~$130-160K/month, solo founder', '@tdinh_me', 'linkedin.com/in/tdinh-me', '', 'typingmind.com', 'Vietnam', 'Built TypingMind in ONE DAY when ChatGPT API launched — made $22K first week', 'not_contacted'),
('Damon Chen', 'Testimonial.to', 'Micro-SaaS', 'Collect and embed video/text testimonials in minutes', '~$70K/month, $800K+ ARR', '@damengchen', 'linkedin.com/in/damengchen', '', 'testimonial.to', 'San Jose, CA', '8 years at Cisco, quit with promise to wife — failed 4 times before success', 'not_contacted'),
('Aurelio Volle', 'WP Umbrella', 'Micro-SaaS', 'WordPress site management platform for agencies', '$110K MRR, 67% YoY growth', '@AurelioVolle', 'linkedin.com/in/aurelio-volle-5b6566193', '', 'wp-umbrella.com', 'Lyon, France', 'Former EU lobbyist with zero tech background, bootstrapped from $7K to $110K MRR', 'not_contacted'),
('Marc Seitz & Iuliia Shnai', 'Papermark', 'Micro-SaaS', 'Open-source DocSend alternative with analytics', '~$75K MRR (~$900K ARR)', '@mfts0', 'linkedin.com/in/marcseitz', '', 'papermark.com', 'Munich, Germany', 'Husband-wife duo, started with a tweet. Iuliia learned to code 2 months before joining', 'not_contacted'),
('Dan Kulkov', 'FounderPal', 'Micro-SaaS', 'AI-powered marketing strategy tools for solopreneurs', '~$10K/month, $215K+ lifetime', '@DanKulkov', 'linkedin.com/in/dan-kulkov-3725b7295', '', 'founderpal.ai', 'Dover', 'Lost his job, built with his wife, $100K revenue in 16 months', 'not_contacted'),
('Jon Yongfook', 'Bannerbear', 'Micro-SaaS', 'API for automated image and video generation', '~$83K MRR, $1M ARR', '@yongfook', '', '', 'bannerbear.com', 'Singapore', 'Journey to $10K MRR went viral on Hacker News. Solo to $1M ARR', 'not_contacted'),
('Ken Savage', 'Launch Club AI', 'Micro-SaaS', 'Reddit marketing tool for startups', '$61K+ MRR, 85%+ margins', '@kensavage', 'linkedin.com/in/kensavage', '', 'launchclub.ai', 'Boston, MA', 'Cracked Reddit algorithm, $0 marketing spend to $30K MRR in 4 months', 'not_contacted'),
('Samuel Rondot', 'useArtemis / StoryShort', 'Micro-SaaS', 'Portfolio: LinkedIn scraping, AI video generator, AI coding tool', '~$35K/month combined', '@samuelrdt', 'linkedin.com/in/samuel-rondot-useartemis', '', 'useartemis.co', 'Lyon, France', 'Former optician, zero coding experience, taught himself from YouTube', 'not_contacted'),
('Cory Zue', 'SaaS Pegasus', 'Micro-SaaS', 'Django boilerplate/starter kit for launching SaaS products', '~$100K+ annual profit', '@czue', 'linkedin.com/in/coryzue', '', 'saaspegasus.com', 'Cape Town, South Africa', 'Former CTO, year 8 of indie hacking', 'not_contacted'),
('Pascal Levy-Garboua', 'Noosa Labs', 'Micro-SaaS', 'Portfolio of acquired micro-SaaS products', '$120K MRR across portfolio', '', '', '', 'noosalabs.com', 'United States', 'Acquires and grows small SaaS. Unique buy and grow strategy', 'not_contacted'),

-- CHROME / SHOPIFY (9)
('Rick Blyth', 'Merch Wizard & KDP Wizard', 'Chrome/Shopify', 'Chrome extensions for Amazon Merch & KDP sellers', '$120K/yr, $500K+ lifetime before exit', '', '', '', 'rickblyth.com', '', 'Built and exited a Chrome extension business while working full-time', 'not_contacted'),
('Justin Albertynas', 'RatePunk', 'Chrome/Shopify', 'Browser extension comparing hotel prices', '$50K+ MRR, 100K+ users', '', 'linkedin.com/in/albertynas', '', 'ratepunk.org', '', 'Proves Chrome extensions are still a viable business', 'not_contacted'),
('Erikas Malisauskas', 'Kaching Appz', 'Chrome/Shopify', 'Portfolio of Shopify apps (Wide Bundles, WideReview)', '$100K+ MRR, $4.3M+ total', '@malisauskasLT', '', '', 'kachingappz.com', '', 'Zero paid marketing ever, pure organic growth to $100K+/mo', 'not_contacted'),
('Saeed Ezzati', 'Superpower ChatGPT', 'Chrome/Shopify', 'Chrome extension that supercharges ChatGPT (200K+ users)', '~$20K-$30K/mo + $150K ARR newsletter', '@eeeziii', 'linkedin.com/in/saeedezzati', '', 'superpowerdaily.com', 'San Francisco, CA', 'Zero ad spend, parlayed user base into six-figure newsletter', 'not_contacted'),
('Mat De Sousa', 'WideBundle', 'Chrome/Shopify', 'Shopify app for product bundles and quantity breaks', '~$55K MRR, 6-person team', '@DsMatie', 'linkedin.com/in/mat-de-sousa-20a365134', '', 'widebundle.com', 'Paris, France', 'Built as a student at 20, failed twice before, no paid ads', 'not_contacted'),
('Rishi Mohan', 'Pika (pika.style)', 'Chrome/Shopify', 'Screenshot beautification tool, open-source side project', '~$3.8K MRR, solo, zero funding', '@thelifeofrishi', 'linkedin.com/in/thelifeofrishi', '', 'pika.style', 'Berlin, Germany', 'Classic #buildinpublic — free tool converted into profitable solo business', 'not_contacted'),
('Erman Kuplu', 'Analyzify', 'Chrome/Shopify', 'Server-side tracking and analytics for Shopify', '~$50K MRR, $0 marketing spend', '@ErmanKuplu', 'linkedin.com/in/ermankuplu', '', 'analyzify.com', 'Tallinn, Estonia', 'Freelancer-to-founder, $0 to $50K MRR in 18 months', 'not_contacted'),
('Ruslan Leteyski', 'Checkout X / Zipchat AI', 'Chrome/Shopify', 'Built alt Shopify checkout to EUR 600K MRR before Shopify killed it', 'EUR 600K MRR at peak', '@leteyski', 'linkedin.com/in/leteyski', '', 'leteyski.com', 'Sofia, Bulgaria', 'Bootstrapped to EUR 600K MRR then got killed by Shopify — platform-risk tale', 'not_contacted'),
('Edmund Yong', 'Easy Folders', 'Chrome/Shopify', 'Chrome extension adding folders to ChatGPT/Claude', '$3,700+ MRR, $42K+ in 6 months', '@edmund_io', '', '', 'easyfolders.io', 'EU', 'Simple AI-wave utility proving timing and simplicity beat complexity', 'not_contacted'),

-- E-COMMERCE / PHYSICAL (15)
('Jocelyn Elizabeth', 'NikNax (Crazy Lamp Lady)', 'E-commerce/Physical', 'Curated secondhand marketplace for vintage items', '$5.2M GMV, 5000+ sellers', '@crazylamplady', '', '', 'niknax.net', '', 'Started from a $5 lamp flip on YouTube, built an entire marketplace', 'not_contacted'),
('April Showers', 'Afro Unicorn', 'E-commerce/Physical', 'Inclusive children''s brand with licensed character merchandise', 'In Walmart, Target, JCPenney', '', '', '', 'afrounicorns.com', '', 'First Black woman-owned fully licensed character brand', 'not_contacted'),
('Mina Elias', 'Supplements (Amazon FBA)', 'E-commerce/Physical', 'Own supplement brand + manages 138 brands on Amazon', '$4M+/yr, $1M profit, 76 employees', '', '', '', '', '', 'Got fired, built a $4M/yr Amazon FBA empire from scratch', 'not_contacted'),
('Tze Hing Chan', 'Subtle Asian Treats', 'E-commerce/Physical', 'Bubble tea plush toys and Asian-themed merchandise', '$19K profit in first 2 months', '', '', '', '', '', 'Started during COVID with $3K, mastered product bundling', 'not_contacted'),
('Sasha Weekes', 'Timber Grove Studios', 'E-commerce/Physical', 'Custom wood shelves and minimalist home decor', '$2K-$10K/month, got acquired', '@timbergrovestudios', '', '', 'timbergrovestudio.com', '', 'Built $10K/mo from home workshop at age 25, then got acquired', 'not_contacted'),
('Jason Rosenbaum', 'Actual Veggies', 'E-commerce/Physical', 'Fresh veggie burgers with real vegetables', '$300K+/month, on track for $20M', '', 'linkedin.com/in/rosenbaumjason', '', 'actualveggies.com', '', 'Side hustle turned $20M food brand in 3 years', 'not_contacted'),
('Kelly Rocklein', 'UGC Pro', 'E-commerce/Physical', 'Creates user-generated content for brands', '$233K/year', '', '', '', 'ugcpro.co', '', 'Built $233K business before getting laid off', 'not_contacted'),
('Kate Kim', 'Caitlyn Minimalist', 'E-commerce/Physical', 'Personalized minimalist jewelry — Etsy + DTC', '~$25M/year, 3M+ Etsy sales', '', 'linkedin.com/company/caitlynminimalist', '', 'caitlynminimalist.com', 'Irvine, CA', 'Vietnamese immigrant — grandfather''s handwriting necklace became Etsy all-time best-seller', 'not_contacted'),
('Erin E. Hooley', 'Bailey''s Blossoms', 'E-commerce/Physical', 'Children''s clothing, started on Etsy', '~$9M/year, 35 employees', '', 'linkedin.com/in/erin-e-hooley-1601947b', '', 'baileysblossoms.com', 'Texas', 'Mom of 6, no degree, bootstrapped $35K Etsy shop into $9M/yr empire', 'not_contacted'),
('Leah Garcia', 'NULASTIN', 'E-commerce/Physical', 'Patented elastin-based beauty products', '$17.5M revenue as solo founder', '@LeahGarciaTV', 'linkedin.com/in/leah-garcia-592988', '', 'nulastin.com', 'Boulder, CO', 'Former pro rodeo athlete, bootstrapped beauty brand to $17.5M solo', 'not_contacted'),
('Sean Busch', 'Puracy / DadMode', 'E-commerce/Physical', 'Natural cleaning products', '$20K launch to $30M+/yr, sold', '@stbusch', 'linkedin.com/in/seantbusch', '', 'puracy.com', 'Austin, TX', 'Serial bootstrapper — $20K to $30M+/yr, sold, now building again', 'not_contacted'),
('Ryan Bartlett', 'True Classic', 'E-commerce/Physical', 'Men''s basics/t-shirt brand, DTC', '$3K to $150M in year 3', '@RyanBartlett', 'linkedin.com/in/rbtct', '', 'trueclassictees.com', 'Los Angeles, CA', 'Failed musician — $100/day Facebook ads into fastest-growing DTC brand', 'not_contacted'),
('Anna Vocino', 'Eat Happy Kitchen', 'E-commerce/Physical', 'Clean-label sauces and spices', '1,300+ stores, $700K crowdfunded', '', 'linkedin.com/in/annavocino', '', 'eathappykitchen.com', 'Santa Ynez Valley, CA', 'Cookbook author who equity-crowdfunded into 1,300+ stores', 'not_contacted'),
('Craig Adam', 'Kitchen Tools (Amazon FBA)', 'E-commerce/Physical', 'Private-label kitchen tools on Amazon', '~$720K/year, solo, zero employees', '', '', '', '', 'United Kingdom', 'UK construction worker, dad of 3, quit after 5 months of FBA', 'not_contacted'),
('Dylan Jacob', 'BruMate', 'E-commerce/Physical', 'Insulated drinkware', '$100M+ revenue, 100% founder-owned', '@dylanbjacob', 'linkedin.com/in/dylan-jacob-50014475', '', 'brumate.com', 'Denver, CO', 'Built $100M brand by age 25, zero employees, zero investors, self-taught', 'not_contacted'),

-- SERVICE BUSINESSES (13)
('Julia Callahan', 'Jubilee Cleaning Co.', 'Service', 'Residential cleaning in rural Pennsylvania', '$100K+/month in under 2 years', '', 'linkedin.com/in/callahanjulia', '', 'jubileecleaning.co', 'Pennsylvania', 'Left 6-figure medical sales, $100K/mo in rural market', 'not_contacted'),
('Stewart Ward', 'Quality Outdoors', 'Service', 'Custom landscaping, hardscapes, outdoor kitchens', 'Multi-million, 1500% growth since 2020', '', 'linkedin.com/in/stewart-ward-37b393166', '', 'qualityoutdoorsva.com', 'Georgia', '2025 Georgia Young Entrepreneur of Year (SBA)', 'not_contacted'),
('Amber Starling', 'Good Witch Cleaning', 'Service', 'Residential cleaning with unique culture', '$467K/year, 6 employees', '', '', '', 'goodwitchcleaning.com', '', 'Started with $100 and a vacuum', 'not_contacted'),
('Neel Parekh', 'MaidThis', 'Service', 'Cleaning for Airbnbs and vacation rentals', '$10M+ total revenue, franchising', '@NeelBParekh', 'linkedin.com/in/neelbparekh', 'neel@maidthis.com', 'maidthis.com', '', 'Niche short-term rental cleaning, franchise model', 'not_contacted'),
('Ginni Saraswati', 'Ginni Media', 'Service', 'Podcast production agency, 30+ shows/week', '$50K+/month recurring', '', 'linkedin.com/in/ginnisaraswati', '', 'ginnimedia.com', '', 'Solo project to global agency, 27 employees, 16 countries', 'not_contacted'),
('Carter Osborne', 'Carter Osborne Tutoring', 'Service', 'High-ticket college essay consulting', '$222K/year, 10 hours/week', '', 'linkedin.com/in/carter-osborne-472a41106', '', 'carterosbornetutoring.com', '', '$222K on 10 hrs/week — incredible leverage', 'not_contacted'),
('Bryan Clayton', 'GreenPal', 'Service', 'On-demand lawn care marketplace', '$30M+/year, bootstrapped', '@bryanMclayton', 'linkedin.com/in/bryan-clayton-a96b33214', '', 'yourgreenpal.com', 'Nashville, TN', 'Mowed lawns in high school, sold first company for $10M, bootstrapped GreenPal to $30M/yr', 'not_contacted'),
('Taylor Hersom', 'Eden Data', 'Service', 'Cybersecurity consulting (Virtual CISO)', '$6M+/year, from Upwork side hustle', '', 'linkedin.com/in/taylorhersom', '', 'edendata.com', 'Austin, TX', 'Upwork gig turned $6M+ consultancy, acquired 2025', 'not_contacted'),
('Austin Houser', 'Base Coat Marketing', 'Service', 'Marketing agency for painting companies', '$1M+/year, 0 to 7 figures in 11 months', '', '', '', 'basecoatmarketing.com', 'Wilmington, NC', 'Niched to painters only, hit $1M+ in under a year', 'not_contacted'),
('Mike Doehla', 'Stronger U Nutrition', 'Service', 'Online nutrition coaching at scale', '$600K/month (~$7.2M/year)', '', 'linkedin.com/in/mike-doehla-75534a116', '', 'strongeru.com', 'New York area', 'Started with cell phone and one coach in garage, $7M+/yr without VC', 'not_contacted'),
('Jacob Fiore', 'DevRize', 'Service', 'Technical recruiting for VC-backed startups', '$240K/year profit', '', 'linkedin.com/in/jacob-f-40b4a672', '', 'devrize.io', 'Denver, CO', 'Former J.P. Morgan analyst, $8K referral bonus model', 'not_contacted'),
('Igor Volovyi', 'Elit-Web', 'Service', 'Digital marketing agency, 120+ employees', '$1.5M+/year, 1,200+ clients', '', 'linkedin.com/in/igor-volovoy', '', 'elit-web.com', 'Kyiv, Ukraine', 'Built 120-person agency, kept profitable through a war', 'not_contacted'),
('Mischa Sigtermans', 'Pixelstart / Stagent', 'Service', 'Solo web design agency, sold for 6 figures', '$120K/year at sale', '', 'linkedin.com/in/mischasigtermans', '', 'stagent.com', 'Haarlem, Netherlands', 'Former DJ, sold agency at age 27', 'not_contacted'),

-- CITY TOUR (7)
('Justin Fenchel', 'BeatBox Beverages', 'City Tour — Austin', 'Party punch/RTD alcohol brand from UT Austin MBA project', '$100M+ gross revenue', '@WellThisJustIn', 'linkedin.com/in/justin-fenchel-36944bb', '', 'beatboxbeverages.com', 'Austin, TX', '5 co-founders pooled $55K, biggest Shark Tank deal ($1M from Mark Cuban)', 'not_contacted'),
('Nathan Latka', 'Founderpath', 'City Tour — Austin', 'Non-dilutive funding for bootstrapped SaaS founders', 'Deployed $50M+ to 125+ founders', '@NathanLatka', 'linkedin.com/in/nathanlatka', '', 'founderpath.com', 'Austin, TX', 'Interviewed 2,500+ founders, now bankrolls anti-VC movement', 'not_contacted'),
('Grantly Neely', 'Granite Education / KnowQo', 'City Tour — Nashville', 'Mindfulness-based test prep software', '~$360K/year, 100% equity', '', 'linkedin.com/in/marshallneely', '', 'granitetestprep.com', 'Nashville, TN', 'Dartmouth grad, bootstrapped education biz with zero capital', 'not_contacted'),
('Praveen Ghanta', 'HiddenLevers / Fraction', 'City Tour — Atlanta', 'Bootstrapped fintech SaaS, sold for 16x revenue', '~$8M ARR at sale', '@truecost', 'linkedin.com/in/pghanta', '', 'fraction.work', 'Atlanta, GA', 'Bootstrapped in Atlanta for 11 years, zero VC, sold for 16x', 'not_contacted'),
('Cynthia Ruff', 'Hashtag Pay Me', 'City Tour — Atlanta', 'Creator pricing tool', 'Georgia Tech Create-X', '', '', '', 'hashtagpayme.com', 'Atlanta, GA', 'Turned down investors to bootstrap creator pricing tool', 'not_contacted'),
('Jared Shusterman', 'SproutLoud', 'City Tour — Miami', 'Marketing automation for brands', '$30M revenue, bootstrapped', '@jshusterman', 'linkedin.com/in/jaredshusterman', '', 'sproutloud.com', 'Fort Lauderdale, FL', 'Started with Bar Mitzvah money as teenager, $30M bootstrapped', 'not_contacted'),
('Jeff Mullarkey', 'RKON Technologies', 'City Tour — Chicago', 'Managed cloud solutions and IT services', '$45M, from $100 bank account', '', 'linkedin.com/in/rkonceo', '', 'rkon.com', 'Chicago, IL', '$100 bank account in 1998 to $45M managed services', 'not_contacted');
